vaadin/vaadin-dialog

vaadin-dialog.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/3)
=> Extend vaadin-overlay to provide a dedicated themable

analysis.json, demo/index.html, test/vaadin-dialog_test.html, vaadin-dialog.html
Fixes #7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/10)
=> Close dialog on outside click by default

bower.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/22)
=> Downgrade themable mixin

analysis.json, vaadin-dialog.html
Fixes https://github.com/vaadin/vaadin-dialog/issues/24
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/26)
=> Link to overlay documentation for styling parts

vaadin-dialog.html
Fixes #23
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/27)
=> Move hardcoded styles to default theme

vaadin-dialog.html
Fixes #28 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/34)
=> exported class-name not aligned with other elements

bower.json, theme/valo/vaadin-dialog.html
Update according to latest updates in Valo styles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/45)
=> Update Valo dependency

src/vaadin-dialog.html
Connected to vaadin/components-team-tasks#308
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/47)
=> Fixed src imports.

src/vaadin-dialog.html, test/vaadin-dialog_test.html
Fixes #36
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/48)
=> Do not fail without template

src/vaadin-dialog.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/50)
=> Align class name with other vaadin elements

src/vaadin-dialog.html, test/vaadin-dialog_test.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/55)
=> Close the overlay on detach. Fixes #54

theme/lumo/vaadin-dialog.html
Fixes #62
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/63)
=> Remove native outline from the overlay part

demo/demos.json, demo/dialog-basic-demos.html
Connected to https://github.com/vaadin/components-team-tasks/issues/347
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/68)
=> Update the custom styling example

.travis.yml, test/vaadin-dialog_test.html, wct.conf.js
Connected to vaadin/components-team-tasks#332
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/69)
=> Use bare module specifiers in the P3 conversion

demo/dialog-basic-demos.html
Fixes #73
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/75)
=> Simplified two first demos: removed Polymer dom-bind

bower.json, theme/material/vaadin-dialog-styles.html, theme/material/vaadin-dialog.html
Connected to vaadin/vaadin-material-styles#49
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/78)
=> Adding theme/material

demo/dialog-basic-demos.html, src/vaadin-dialog.html, test/vaadin-dialog_test.html
Fixes #90
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/91)
=> add an `ariaLabel` property to forward to the overlay

analysis.json, src/vaadin-dialog.html, test/vaadin-dialog_renderer-test.html
Please `bower link vaadin-overlay` from `throw-error` branch before testing.
Requires https://github.com/vaadin/vaadin-overlay/pull/104
Connected to https://github.com/vaadin/components-team-tasks/issues/391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/93)
=> Throw error when template and renderer are used simultaneously

demo/dialog-basic-demos.html, demo/index.html
Fixes #95 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/94)
=> Changed demos to use renderer function by default

demo/dialog-basic-demos.html
Fixes #100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/101)
=> Remove dom-bind from the demos

src/vaadin-dialog.html
Connected to vaadin/components-team-tasks#401
Connected to vaadin/components-team-tasks#402
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/103)
=> Align renderer API docs with context-menu [skip ci]

.travis.yml, bower.json, demo/dialog-basic-demos.html, demo/index.html, src/vaadin-dialog.html, test/vaadin-dialog_test.html
Connected to vaadin/vaadin-themable-mixin#12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/42)
=> Propagate theme attribute to internal overlay. 

bower.json, src/vaadin-dialog.html, test/vaadin-dialog_renderer-test.html
Connected to https://github.com/vaadin/components-team-tasks/issues/409
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/107)
=> Manual rendering of the content

demo/dialog-basic-demos.html
Fixes #115 
Fixes #114
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/117)
=> Fix renderer use in the demos [skip ci]

demo/dialog-basic-demos.html, src/vaadin-dialog.html
Connected to https://github.com/vaadin/components-team-tasks/issues/416
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/118)
=> Improve renderers docs [skip ci]

demo/dialog-basic-demos.html, demo/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/125)
=> Remove iron-ajax from scrollable demo [skip ci]

src/vaadin-dialog-resizable-mixin.html, test/vaadin-dialog_draggable-resizable-test.html
=> Resize event

src/vaadin-dialog.html, test/vaadin-dialog_draggable-resizable-test.html
=> Only calls overlay#bringToFront on modeless dialog

src/vaadin-dialog-draggable-mixin.html, src/vaadin-dialog-resizable-mixin.html, src/vaadin-dialog.html, test/vaadin-dialog_draggable-resizable-test.html
=> Disable multitouch dragging and resizing

src/vaadin-dialog-draggable-mixin.html, test/vaadin-dialog_draggable-resizable-test.html
Fixes https://github.com/vaadin/vaadin-dialog-flow/issues/174
=> Prevent touchstart on desktop

src/vaadin-dialog-resizable-mixin.html
=> fix: Fix resizing on Safari

src/vaadin-dialog-resizable-mixin.html
Backport https://github.com/vaadin/vaadin-dialog/pull/157
=> fix: Fix resizing on Safari [2.3]

@types/interfaces.d.ts, gen-tsd.json, src/vaadin-dialog.html
=> fix: TS fixes based on findings [skip ci]

src/vaadin-dialog-resizable-mixin.html, test/.eslintrc.json, test/vaadin-dialog_draggable-resizable-test.html
=> fix: dialog overlay scrolling (#168)

src/vaadin-dialog-resizable-mixin.html, test/vaadin-dialog_draggable-resizable-test.html
Related bug https://bugs.webkit.org/show_bug.cgi?id=26559
=> Don't use min-height for content part

src/vaadin-dialog-resizable-mixin.html, test/vaadin-dialog_draggable-resizable-test.html
Related bug https://bugs.webkit.org/show_bug.cgi?id=26559
=> fix: don't use min-height for content part (#172)

src/vaadin-dialog-resizable-mixin.html, test/vaadin-dialog_draggable-resizable-test.html
Co-authored-by: diegocardoso <diego@vaadin.com>
=> fix: don't overflow scrollable full height content (#175)

src/vaadin-dialog.html
Connected to vaadin/vaadin-core#257
=> docs: add JSDoc for attributes [skip ci]

src/vaadin-dialog-resizable-mixin.html, test/vaadin-dialog_draggable-resizable-test.html
=> fix: prevent incorrect overflow in Safari (#180)

src/vaadin-dialog-draggable-mixin.html, test/.eslintrc.json, test/vaadin-dialog_draggable-resizable-test.html
=> fix: support dragging from a draggable node inside another shadow root (#188)
