vaadin/vaadin-dialog

- vaadin-dialog.html
The previous documentation said "See `<vaadin-overlay>`'s styling documentation for themable parts". However, there is no styling documentation for `<vaadin-overlay>` and since it's an element for internal use anyway, it's a bad reference for docs.
List the shadow parts in `<vaadin-dialog>`'s documentation instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/4)
> Improve styling documentation

- demo/index.html
DX tests finding, developers sometimes prefer to look at examples rather than at docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/12)
> Add example with no-close-on-esc and no-close-on-outside-click

- README.md
There was a missing pair of template tag inside custom-element-demo in order for the inline demo to work. I also added polyfill so the demo can work on non-native-polyfill browsers as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/29)
> Added missing template tag and polyfill

- analysis.json
- vaadin-dialog.html
Fixes #31
List of changes: 
- Workaround with extending implemented to get rid of multiple unintentional Polymer.Element APIs
- `VaadinDialogOverlay` mark as `@private`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/30)
> Get rid of multiple Polymer.Element APIs, mark VaadinDialogOverlay as @private

- test/vaadin-dialog_test.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/33)
> Send `key` in keyboard events, because it is used in overlay

- src/vaadin-dialog.html
- test/vaadin-dialog_test.html
We apparently have copy-pasted Templatizer code from the `vaadin-context-menu` in several components, including this one. These `instanceProps` (see the [context-menu API docs](https://github.com/vaadin/vaadin-context-menu/blob/master/src/vaadin-context-menu.html#L166)) do not make any sense here and should be removed.
Also added the tests for data binding, based on vaadin/vaadin-notification#54
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/58)
> Add tests for data binding, remove unused instanceProps

- theme/lumo/vaadin-dialog.html
Use the vaadin-overlay opening and closing animation support.
Depends on https://github.com/vaadin/vaadin-lumo-styles/commit/fc3e8ad0b363dd3c7bcaacf1c5968778ed186d54
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/59)
> Refine animations

- theme/lumo/vaadin-dialog.html
The animations feel a bit slow when you have to open and close many dialogs within a short period of time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/71)
> Speed up animations

- theme/lumo/vaadin-dialog.html
It’s a known optical illusion, that objects which are mathematically vertically centered appear to be lower than the center.
We can compensate for that by using a transform calculation that moves the dialog upwards by a certain ratio between the dialog height and viewport height. The magic number `20` was selected by “eyeballing” the results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/70)
> Adjust for optical vertical centering

- src/vaadin-dialog.html
- test/vaadin-dialog_test.html
Fixes #76 
Connected to vaadin/vaadin-dialog-flow#70
Fixes vaadin/vaadin-dialog-flow#67
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/77)
> Add default content minWidth to prevent collapsing to zero

- demo/dialog-basic-demos.html
Connects to "Guidelines for component examples"
- Confirm dialog example (convert the current generic “Can Only Be Closed with Buttons Inside It”)
- Use “OK” instead of “Ok”, and add a theme="primary" for those buttons
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/82)
> Create confirm dialog demo

- demo/dialog-basic-demos.html
Connects to "Guidelines for component examples": Add scrollable dialog, with a fixed button footer and max-height (doesn’t grow bigger than the browser viewport)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/83)
> Add scrollable dialog demo

- .travis.yml
- analysis.json
- bower.json
- demo/dialog-basic-demos.html
- src/vaadin-dialog.html
- test/test-suites.js
- test/vaadin-dialog_renderer-test.html
- test/vaadin-dialog_test.html
Fixes #87
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog/88)
> Added renderer function

- src/vaadin-dialog-draggable-mixin.html
- src/vaadin-dialog.html
- test/vaadin-dialog_draggable-resizable-test.html
By adding a class "draggable" to an element, user can mark it as an area from which the dialog can be dragged.
Part of vaadin/vaadin-dialog-flow#165
> Add ability to mark child element as draggable

- @types/interfaces.d.ts
- bower.json
- gen-tsd.json
- magi-p3-post.js
- package.json
- src/vaadin-dialog-draggable-mixin.html
- src/vaadin-dialog-resizable-mixin.html
- src/vaadin-dialog.html
Fixes #156
Generated TS definitions look like this:
```ts
import {PolymerElement} from '@polymer/polymer/polymer-element.js';
import {OverlayElement} from '@vaadin/vaadin-overlay/src/vaadin-overlay.js';
import {ElementMixin} from '@vaadin/vaadin-element-mixin/vaadin-element-mixin.js';
import {FlattenedNodesObserver} from '@polymer/polymer/lib/utils/flattened-nodes-observer.js';
import {ThemePropertyMixin} from '@vaadin/vaadin-themable-mixin/vaadin-theme-property-mixin.js';
import {DialogDraggableMixin} from './vaadin-dialog-draggable-mixin.js';
import {DialogResizableMixin} from './vaadin-dialog-resizable-mixin.js';
import {IronResizableBehavior} from '@polymer/iron-resizable-behavior/iron-resizable-behavior.js';
import {mixinBehaviors} from '@polymer/polymer/lib/legacy/class.js';
import …
```
> feat: prepare for TS defs generation

- src/vaadin-dialog-draggable-mixin.html
- src/vaadin-dialog-resizable-mixin.html
- src/vaadin-dialog.html
- test/vaadin-dialog_draggable-resizable-test.html
Fixes #161 
The previous logic tried to prevent scrolling the document on the background by canceling all touchmove events. This PR reverts the change, which means that the document is again scrollable in case the touch sequence starts over non-draggable/non-scrollable dialog content. This, however, is a much lesser evil than not being able to scroll the dialog content at all on a touch device.
> fix: don't prevent touchmove events inside the dialog

- src/vaadin-dialog-draggable-mixin.html
- src/vaadin-dialog-resizable-mixin.html
- src/vaadin-dialog.html
- test/vaadin-dialog_draggable-resizable-test.html
> fix: don't prevent touchmove events inside the dialog (#164)

- src/vaadin-dialog-resizable-mixin.html
- test/.eslintrc.json
- test/vaadin-dialog_draggable-resizable-test.html
> fix: dialog overlay scrolling (#168)

- src/vaadin-dialog-resizable-mixin.html
- test/vaadin-dialog_draggable-resizable-test.html
The change is required for Safari
Fix candidate for https://github.com/vaadin/vaadin-dialog-flow/issues/196
Couldn't find a fix for iOS10 Safari
> fix: don't overflow scrollable full height content

- src/vaadin-dialog-resizable-mixin.html
- test/vaadin-dialog_draggable-resizable-test.html
Fixes https://github.com/vaadin/vaadin-dialog-flow/issues/204
See the description of the actual Safari issue here: https://github.com/vaadin/vaadin-dialog-flow/issues/204#issuecomment-661874922
The fix can be tested with the demo: https://github.com/vaadin/vaadin-dialog-flow/commit/576c1405bc95ceba2d7dcffaff68d1045d23e739
This should not re-introduce regression from #172 because `min-height` is set on the different element.
> fix: prevent incorrect overflow in Safari

- src/vaadin-dialog-draggable-mixin.html
- test/.eslintrc.json
- test/vaadin-dialog_draggable-resizable-test.html
fixes https://github.com/vaadin/vaadin-dialog-flow/issues/216
> fix: support dragging from a draggable node inside another shadow root

- src/vaadin-dialog-draggable-mixin.html
- src/vaadin-dialog.html
- test/vaadin-dialog_draggable-resizable-test.html
Relates to https://github.com/vaadin/vaadin-dialog/issues/190
The "draggable-leaf-only" class name can specify elements that can't be dragged by their non-draggable children
To fix #190, bump the Web Component version of the Flow counterpart and add "draggable-leaf-only" class name to the [container element](https://github.com/vaadin/vaadin-dialog-flow/blob/master/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java#L63).
> fix: add draggable-leaf-only marker class name

- src/vaadin-dialog.html
Instead of setting `max-width: none` when a dialog is dragged or resized directly to the node style attribute, use a custom attribute which is used in a CSS selector to apply that style. It will prevent a custom `max-width` from being reset when user resizes or drags the dialog.
Part of https://github.com/vaadin/vaadin-dialog-flow/issues/168
> refactor: move how overlay max-width is set
